name: Update AdGuardHome
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/workflows/delete-old-workflows.yml"
      - ".github/workflows/update-clash.meta-release.yml"
      - ".github/workflows/update-release.yml"
      - ".github/workflows/update-dashboard.yml"
      - ".github/workflows/update-adguardhome.yml"

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Set variables
      run: |
        echo "MICROSOFT_CN_URL=https://rules.kr328.app/microsoft@cn.yaml" >> $GITHUB_ENV
        echo "APPLE_CN_URL=https://rules.kr328.app/apple@cn.yaml" >> $GITHUB_ENV
        echo "GOOGLE_CN_URL=https://rules.kr328.app/google@cn.yaml" >> $GITHUB_ENV
        echo "CATEGORY_GAMES_CN_URL=https://rules.kr328.app/category-games@cn.yaml" >> $GITHUB_ENV
        echo "PROXY_URL=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy.list" >> $GITHUB_ENV
        echo "CHINAMAX_URL=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax.list" >> $GITHUB_ENV

    - name: Generate adguardhome-whitelist
      env:
          SED1: sed '/^\s*#/d' | sed '/payload:/d' | sed 's/- "+./[\//g' | sed 's/- "/[\//g' | sed 's/"$/\/]https:\/\/doh.pub\/dns-query/g' | sed '/^\s*$/d'
          SED2: sed '/^\s*#/d' | sed '/^PROCESS-NAME,/d' | sed '/^\s*IP-CIDR/d' | sed 's/DOMAIN,/[\//g' | sed 's/DOMAIN-SUFFIX,/[\//g' | sed 's/DOMAIN-KEYWORD,/[\//g' | sed 's/$/\/]https:\/\/doh.pub\/dns-query/'
          SED3: sed '/^\s*#/d' | sed '/^\s*IP-CIDR/d' | sed 's/DOMAIN,/[\//g' | sed 's/DOMAIN-SUFFIX,/[\//g' | sed 's/DOMAIN-KEYWORD,/[\//g' | sed 's/$/\/]https:\/\/dns.google\/dns-query/'
      run: |
        echo "update_version=$(date +%Y-%m-%d)" >> ${GITHUB_ENV}
        mkdir -p ./tmp
        mkdir -p ./adgtest
        rm -rf ./adgtest/*
        curl -sSL $MICROSOFT_CN_URL | ${{ env.SED1 }} > ./tmp/temp-whitelist.txt
        curl -sSL $APPLE_CN_URL | ${{ env.SED1 }} >> ./tmp/temp-whitelist.txt
        curl -sSL $GOOGLE_CN_URL | sed '/googleapis.cn/d'| ${{ env.SED1 }} >> ./tmp/temp-whitelist.txt
        curl -sSL $CHINAMAX_URL |  ${{ env.SED2 }} >> ./tmp/temp-whitelist.txt
        curl -sSL $PROXY_URL |  ${{ env.SED3 }} >> ./tmp/temp-whitelist.txt
        cat <<EOF >> ./tmp/temp-whitelist.txt
        https://dns.google/dns-query
        https://cloudflare-dns.com/dns-query
        https://dns.quad9.net/dns-query
        EOF
        cat ./tmp/temp-whitelist.txt > ./adgtest/adguardhome-whitelist.txt

    - name: Generate adguardhome-blacklist
      env:
          SED: sed '/^\s*#/d' | sed '/^\s*IP-CIDR/d' | sed 's/DOMAIN,/[\//g' | sed 's/DOMAIN-SUFFIX,/[\//g' | sed 's/DOMAIN-KEYWORD,/[\//g' | sed 's/$/\/]https:\/\/dns.google\/dns-query/'
      run: |
        curl -sSL $PROXY_URL |  ${{ env.SED }} > ./tmp/temp-blacklist.txt
        cat <<EOF >> ./tmp/temp-blacklist.txt
        https://doh.pub/dns-query
        https://dns.alidns.com/dns-query
        EOF
        cat ./tmp/temp-blacklist.txt > ./adgtest/adguardhome-blacklist.txt
        rm -rf ./tmp

    - name: Commit and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add . && git commit -m "更新于 ${update_version}" || exit 0
        git push -f

    - name: Purge jsDelivr CDN cache
      uses: gacts/purge-jsdelivr-cache@v1
      with:
        url: |
          https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/adgtest/adguardhome-whitelist.txt
          https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/adgtest/adguardhome-blacklist.txt
