name: Auto task
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

env:
  download_url: https://github.com/MetaCubeX/Clash.Meta/releases/download

jobs:
  create-test-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true
          repo: DustinWin/Clash-Files

      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "download_version=${download_version}" >> ${GITHUB_ENV}

      - name: Download and unzip `upx`
        run: |
          wget https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-amd64_linux.tar.xz
          tar xf upx-4.0.2-amd64_linux.tar.xz

      - name: Download and compress `Clash.Meta core`
        run: |
          mkdir -p ./tmp
          download_version=$(curl -sL https://api.github.com/repos/MetaCubeX/Clash.Meta/releases/tags/Prerelease-Alpha | grep linux-arm64 | head -n 1 | sed 's_.gz.*__;s_.*arm64-__')
          wget "${download_url}/Prerelease-Alpha/clash.meta-linux-arm64-${download_version}.gz" -O - | gunzip -c > ./tmp/clash.meta-linux-arm64
          chmod +x ./tmp/clash.meta-linux-arm64
          ./upx-4.0.2-amd64_linux/upx ./tmp/clash.meta-linux-arm64
          wget -P ./tmp "${download_url}/Prerelease-Alpha/clash.meta-windows-amd64-${download_version}.zip"
          unzip "./tmp/clash.meta-windows-amd64-${download_version}.zip" -d ./tmp
          mv "./tmp/clash.meta-windows-amd64.exe" "./tmp/clash-meta.exe"
          rm -f "./tmp/clash.meta-windows-amd64-${download_version}.zip"
          rm -rf upx*

      - name: Put together user.yaml
        run: |
          mkdir -p ./tmp
          curl -sSL https://raw.githubusercontent.com/DustinWin/Clash-Files/main/MyConfig/front-user.yaml > ./tmp/temp-user.txt
          curl -sSL https://gitea.com/XIU2/TrackersListCollection/raw/branch/master/all.txt | grep -i "\.[A-Z]" | sed 's/^.*\/\///g' | sed 's/:.*\/.*//g' | sed "s/^/    - '/;s/$/'/" >> ./tmp/temp-user.txt
          curl -sSL https://raw.githubusercontent.com/DustinWin/Clash-Files/main/MyConfig/later-user.yaml >> ./tmp/temp-user.txt

      - name: Move files
        run: |
          mkdir -p ./publish
          cp ./tmp/* ./publish
          cat ./tmp/temp-user.txt > ./publish/user.yaml
          rm -rf ./tmp
          cd ./publish || exit 1

      - name: Release and upload assets
        uses: softprops/action-gh-release@v0.1.6
        with:
          name: latest
          tag_name: latest
          draft: false
          prerelease: false
          files: |
            ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git push assets to "release" branch
        run: |
          cd ./publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Purge jsdelivr CDN
        run: |
          cd ./publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
