name: Update Yacd-meta
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/workflows/delete-old-workflows.yml"
      - ".github/workflows/update-adguardhome.yml"
      - ".github/workflows/update-clash.meta-release.yml"
      - ".github/workflows/update-release.yml"

env:
  download_version: ''

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Get version
      run: |
        download_version=$(curl -sSL https://api.github.com/repos/MetaCubeX/Yacd-meta/releases | grep tag_name | head -n 1 | sed 's/.*v/v/g' | sed 's/",$//')
        echo "download_version=${download_version}" >> ${GITHUB_ENV}

    - name: Download `Yacd-meta`
      run: |
        mkdir -p ./tmp
        wget -P ./tmp https://github.com/MetaCubeX/yacd/archive/gh-pages.zip
        unzip ./tmp/gh-pages.zip -d ./tmp
        rm -f ./tmp/*.zip
        tar -czf ./tmp/Yacd-meta.tar.gz -C ./tmp/Yacd-meta-gh-pages
        rm -rf ./tmp/Yacd-meta-*

    - name: Move `Yacd-meta`
      run: |
        mkdir -p ./Yacd-meta
        rm -rf ./Yacd-meta/*
        cp ./tmp/* ./Yacd-meta
        rm -rf ./tmp

    - name: Commit and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add . && git commit -m "更新 Yacd-meta 至 ${download_version}" || exit 0
        git push -f

    - name: Purge jsDelivr CDN cache
      uses: gacts/purge-jsdelivr-cache@v1
      with:
        url: |
          https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/Yacd-meta/Yacd-meta.tar.gz
