name: Update release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

env:
  download_url: https://github.com/MetaCubeX/Clash.Meta/releases/download

jobs:
  create-test-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true
          repo: DustinWin/clash-tools

      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "download_version=${download_version}" >> ${GITHUB_ENV}

      - name: Download and unzip `upx`
        run: |
          mkdir -p ./tmp
          upx_version=$(curl -sSL https://api.github.com/repos/upx/upx/releases | grep tag_name | head -n 1 | sed 's/.*v/v/g' | sed 's/",$//')
          upx_version_nov=$(curl -sSL https://api.github.com/repos/upx/upx/releases | grep tag_name | head -n 1 | sed 's/.*v//g' | sed 's/",$//')
          echo "upx_version=${upx_version}" >> ${GITHUB_ENV}
          echo "upx_version_nov=${upx_version_nov}" >> ${GITHUB_ENV}
          wget -P ./tmp "https://github.com/upx/upx/releases/download/${upx_version}/upx-${upx_version_nov}-amd64_linux.tar.xz"
          tar -xf "./tmp/upx-${upx_version_nov}-amd64_linux.tar.xz" -C ./tmp
          rm -f ./tmp/*.tar.xz

      - name: Download and compress `Clash.Meta core`
        run: |
          download_version=$(curl -sL https://api.github.com/repos/MetaCubeX/Clash.Meta/releases/tags/Prerelease-Alpha | grep linux-arm64 | head -n 1 | sed 's_.gz.*__;s_.*arm64-__')
          wget "${download_url}/Prerelease-Alpha/clash.meta-linux-arm64-${download_version}.gz" -O - | gunzip -c > ./tmp/clash.meta-linux-arm64
          chmod +x ./tmp/clash.meta-linux-arm64
          ./tmp/upx-${upx_version_nov}-amd64_linux/upx ./tmp/clash.meta-linux-arm64
          wget -P ./tmp "${download_url}/Prerelease-Alpha/clash.meta-windows-amd64-${download_version}.zip"
          unzip "./tmp/clash.meta-windows-amd64-${download_version}.zip" -d ./tmp
          rm -f ./tmp/*.zip
          mv "./tmp/clash.meta-windows-amd64.exe" "./tmp/clash-meta.exe"
          rm -rf ./tmp/upx*

      - name: Move files
        run: |
          mkdir -p ./publish
          cp ./tmp/* ./publish
          rm -rf ./tmp
          cd ./publish || exit 1

      - name: Release and upload assets
        uses: softprops/action-gh-release@v0.1.6
        with:
          name: latest
          tag_name: latest
          draft: false
          prerelease: false
          files: |
            ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git push assets to "release" branch
        run: |
          cd ./publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Purge jsdelivr CDN
        run: |
          cd ./publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
