name: Update Clash.Meta release
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Input version, such as "v1.14.3"'
        required: true
        type: string

env:
  download_version: ${{ github.event.inputs.tag }}
  download_url: https://github.com/MetaCubeX/Clash.Meta/releases/download

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Delete old `Clash.Meta core`
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git rm -f ./Clash.Meta-Release/*
        git commit -m "Delete old Clash.Meta release"
        git push

    - name: Download and unzip `upx`
      run: |
        wget https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-amd64_linux.tar.xz
        tar xf upx-4.0.2-amd64_linux.tar.xz

    - name: Download and compress `Clash.Meta core`
      run: |
        echo "download_version=${download_version}" >> ${GITHUB_ENV}
        mkdir -p ./tmp
        wget "${download_url}/${download_version}/clash.meta-linux-arm64-${download_version}.gz" -O - | gunzip -c > ./tmp/clash.meta-linux-arm64
        chmod +x ./tmp/clash.meta-linux-arm64
        ./upx-4.0.2-amd64_linux/upx ./tmp/clash.meta-linux-arm64
        wget -P ./tmp "${download_url}/${download_version}/clash.meta-windows-amd64-${download_version}.zip"
        unzip "./tmp/clash.meta-windows-amd64-${download_version}.zip" -d ./tmp
        mv "./tmp/clash.meta-windows-amd64.exe" "./tmp/clash-meta.exe"
        rm -f "./tmp/clash.meta-windows-amd64-${download_version}.zip"
        rm -rf upx*

    - name: Move `Clash.Meta core` to `Clash.Meta-Core` directory
      run: |
        mkdir -p ./Clash.Meta-Release
        cp ./tmp/* ./Clash.Meta-Release
        rm -rf ./tmp

    - name: Commit and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add . && git commit -m "更新 Clash.Meta 内核至 ${download_version}" || exit 0
        git push

    - name: Purge jsDelivr CDN cache
      uses: gacts/purge-jsdelivr-cache@v1
      with:
        url: |
          https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/Clash.Meta-Release/clash.meta-linux-arm64
