name: Update Yacd-meta
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Download and move `Yacd-meta`
      run: |
        mkdir -p ./Yacd-meta
        rm -rf ./Yacd-meta/*
        cd ./Yacd-meta
        curl -o gh-pages.zip -L https://github.com/MetaCubeX/yacd/archive/gh-pages.zip && unzip gh-pages.zip
        tar -czvf Yacd-meta.tar.gz gh-pages/
        

    - name: Commit and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add . && git commit -m "更新 Yacd-meta" || exit 0
        git push

    - name: Purge jsDelivr CDN cache
      uses: gacts/purge-jsdelivr-cache@v1
      with:
        url: |
          https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/Yacd-meta/Yacd-meta.tar.gz
