name: Update AdGuardHome
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - mains
    paths-ignore:
      - "**/README.md"

env:
  download_version: ''
  download_url: https://github.com/AdguardTeam/AdGuardHome/releases/download

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Download and unzip `upx`
      run: |
        mkdir -p ./tmp
        upx_version=$(curl -sSL https://api.github.com/repos/upx/upx/tags | grep name | head -n 1 | sed 's/.*v/v/g' | sed 's/",$//')
        upx_version_nov=$(curl -sSL https://api.github.com/repos/upx/upx/tags | grep name | head -n 1 | sed 's/.*v//g' | sed 's/",$//')
        echo "upx_version=${upx_version}" >> ${GITHUB_ENV}
        echo "upx_version_nov=${upx_version_nov}" >> ${GITHUB_ENV}
        wget -P ./tmp "https://github.com/upx/upx/releases/download/${upx_version}/upx-${upx_version_nov}-amd64_linux.tar.xz"
        tar -xf "./tmp/upx-${upx_version_nov}-amd64_linux.tar.xz" -C ./tmp

    - name: Download and compress `AdGuardHome`
      run: |
        download_version=$(curl -sSL https://api.github.com/repos/AdguardTeam/AdGuardHome/tags | grep name | head -n 1 | sed 's/.*v/v/g' | sed 's/",$//')
        echo "download_version=${download_version}" >> ${GITHUB_ENV}
        wget "${download_url}/${download_version}/AdGuardHome_linux_arm64.tar.gz" -O - | tar -zxvf - -C ./tmp/
        chmod +x ./tmp/AdGuardHome/AdGuardHome
        ./tmp/upx-${upx_version_nov}-amd64_linux/upx --best ./tmp/AdGuardHome/AdGuardHome

    - name: Move `AdGuardHome` to `AdGuardHome` directory
      run: |
        mkdir -p ./AdGuardHome
        rm -rf ./AdGuardHome/*
        cp ./tmp/AdGuardHome/AdGuardHome ./AdGuardHome/
        rm -rf ./tmp

    - name: Commit and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add . && git commit -m "更新 AdGuardHome 至 ${download_version}" || exit 0
        git push

    - name: Purge jsDelivr CDN cache
      uses: gacts/purge-jsdelivr-cache@v1
      with:
        url: |
          https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/AdGuardHome/AdGuardHome
